os: linux
dist: trusty

language: perl

perl:
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  global:
    - JOBS=3
    - PERL_MM_USE_DEFAULT=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
  jobs:
    - OPENSSL_VERSION=1.1.1h
    - OPENSSL_VERSION=1.1.0l
    - OPENSSL_VERSION=1.0.2u
    - OPENSSL_VERSION=1.0.1u
    - OPENSSL_VERSION=1.0.0t
    - OPENSSL_VERSION=0.9.8zh
    - LIBRESSL_VERSION=3.1.4
    - LIBRESSL_VERSION=3.0.2
    - LIBRESSL_VERSION=2.9.2
    - LIBRESSL_VERSION=2.8.3
    - LIBRESSL_VERSION=2.7.5
    - LIBRESSL_VERSION=2.2.1

jobs:
  exclude:
  - perl: "5.8"
    env: OPENSSL_VERSION=1.1.0l
  - perl: "5.8"
    env: OPENSSL_VERSION=1.1.1h
  - perl: "5.8"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.8"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.8"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.8"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.8"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.8"
    env: LIBRESSL_VERSION=3.1.4
  - perl: "5.10"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.10"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.10"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.10"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.10"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.10"
    env: LIBRESSL_VERSION=3.1.4
  - perl: "5.12"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.12"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.12"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.12"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.12"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.12"
    env: LIBRESSL_VERSION=3.1.4
  - perl: "5.14"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.14"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.14"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.14"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.14"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.14"
    env: LIBRESSL_VERSION=3.1.4
  - perl: "5.16"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.16"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.16"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.16"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.16"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.16"
    env: LIBRESSL_VERSION=3.1.4
  - perl: "5.18"
    env: LIBRESSL_VERSION=2.2.1
  - perl: "5.18"
    env: LIBRESSL_VERSION=2.7.5
  - perl: "5.18"
    env: LIBRESSL_VERSION=2.8.3
  - perl: "5.18"
    env: LIBRESSL_VERSION=2.9.2
  - perl: "5.18"
    env: LIBRESSL_VERSION=3.0.2
  - perl: "5.18"
    env: LIBRESSL_VERSION=3.1.4

cache:
  directories:
  - openssl_version_cache

before_install:
  - mkdir -p openssl_version_cache/src
  - mkdir -p openssl_version_cache/build

install:
  - |
    if [ -n "$OPENSSL_VERSION" ] && [ ! -f openssl_version_cache/src/openssl-$OPENSSL_VERSION.tar.gz ]; then
      case "$OPENSSL_VERSION" in
        0.9.8*)
          SRC_OLD_DIR=0.9.x
          ;;
        *)
          SRC_OLD_DIR="$(echo "$OPENSSL_VERSION" | sed -e 's/[a-z]*$//')"
          ;;
      esac
      wget -P openssl_version_cache/src https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz ||
        wget -P openssl_version_cache/src https://www.openssl.org/source/old/$SRC_OLD_DIR/openssl-$OPENSSL_VERSION.tar.gz
    fi
  - |
    if [ -n "$LIBRESSL_VERSION" ] && [ ! -f openssl_version_cache/src/libressl-$LIBRESSL_VERSION.tar.gz ]; then
      wget -P openssl_version_cache/src https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$LIBRESSL_VERSION.tar.gz
    fi

script:
  - |
    if [ -n "$OPENSSL_VERSION" ]; then
       SSL_LIB_NAME_VER=openssl-$OPENSSL_VERSION
    else
       SSL_LIB_NAME_VER=libressl-$LIBRESSL_VERSION
    fi
    if [ ! -d openssl_version_cache/build/$SSL_LIB_NAME_VER ]; then
      if [ ! -d openssl_version_cache/src/$SSL_LIB_NAME_VER ]; then
        cd openssl_version_cache/src
        tar xzf $SSL_LIB_NAME_VER.tar.gz || exit 1
        cd ../..
      fi
      if [ ! -d openssl_version_cache/src/$SSL_LIB_NAME_VER ]; then
        echo "ERROR Dir openssl_version_cache/src/SSL_LIB_NAME_VER does not exist" && exit 1
      fi
      cd openssl_version_cache/src/$SSL_LIB_NAME_VER
      if [ "$OPENSSL_VERSION" = "1.0.0t" ] || [ "$OPENSSL_VERSION" = "0.9.8zh" ]; then
        ./Configure linux-x86_64 --prefix=$PWD/../../build/openssl-$OPENSSL_VERSION --openssldir=$PWD/../../build/openssl-$OPENSSL_VERSION/ssl shared -Wa,--noexecstack > build.log 2>&1 || (cat build.log && exit 1)
        make > build.log 2>&1 || (cat build.log && exit 1)
        make install_sw > build.log 2>&1 || (cat build.log && exit 1)
        make install_ssldirs > build.log 2>&1 || (cat build.log && exit 1)
      elif [ -n "$OPENSSL_VERSION" ]; then
        ./Configure linux-x86_64 --prefix=$PWD/../../build/openssl-$OPENSSL_VERSION --openssldir=$PWD/../../build/openssl-$OPENSSL_VERSION/ssl enable-shared -Wa,--noexecstack > build.log 2>&1 || (cat build.log && exit 1)
        make -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
        make install_sw > build.log 2>&1 || (cat build.log && exit 1)
        make install_ssldirs > build.log 2>&1 || (cat build.log && exit 1)
      else
        # LibreSSL
        ./configure --prefix=$PWD/../../build/$SSL_LIB_NAME_VER
        make -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
        make install > build.log 2>&1 || (cat build.log && exit 1)
      fi
      cd ../../..
    fi
  - grep -H _VERSION_NUMBER $PWD/openssl_version_cache/build/$SSL_LIB_NAME_VER/include/openssl/opensslv.h # show what version it thinks it is
  - OPENSSL_PREFIX=$PWD/openssl_version_cache/build/$SSL_LIB_NAME_VER LD_LIBRARY_PATH=$PWD/openssl_version_cache/build/$SSL_LIB_NAME_VER/lib perl Makefile.PL
  - make
  - make test
